repositories:
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: elasticsearch #Repo Name
  url: https://helm.elastic.co
- name: kibana
  url: https://helm.elastic.co
releases:
- name: springapp
  namespace: dev
  chart: ./demochart2
  version: 0.2.0
  set:
  - name: replicaCount
    value: "2"
  installed: true
- name: maven-web-app
  namespace: prod
  chart: ./demochart
  version: 0.2.0
  set:
  - name: replicaCount  #This replicaCount will override that of the values.yml file
    value: "10"
  installed: true
  #values:
  #- values.yaml you can add a custom value file and rference it
  #value: "3"
   # - name: service.port
      #value: "8080"
- name: prometheus
  namespace: apm
  chart: prometheus/prometheus
  installed: true
- name: ingress-nginx  #This is a third party app for traffic
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  installed: true
- name: elasticsearch  #This will be the release name
  namespace: elasticsearch
  chart: elasticsearch/elasticsearch #chartName
  installed: true
- name: kibana  #This will be the release name
  namespace: elasticsearch
  chart: kibana/kibana  #chartName
  installed: true